export const users = [
  {
    _id: '669b7e13a0964a16329e40e0',
    index: 0,
    guid: 'fd34de92-ccbe-4702-89b4-fdc9a16f9906',
    isActive: true,
    balance: '$2,386.15',
    picture: 'http://placehold.it/32x32',
    age: 22,
    eyeColor: 'blue',
    name: 'William Lawson',
    gender: 'male',
    company: 'ZEPITOPE',
    email: 'williamlawson@zepitope.com',
    phone: '+1 (988) 536-2313',
    address: '427 Calder Place, Stevens, Palau, 4710',
    about:
      'Eiusmod do quis pariatur excepteur commodo enim sunt ut labore in pariatur quis. Enim est commodo non esse laboris sit id ea labore nostrud qui. Dolore eu aliqua mollit ex do laboris sint labore laborum. In anim cillum magna amet incididunt occaecat reprehenderit eu officia eu elit labore nostrud ipsum. Laborum tempor do ea velit deserunt. Ullamco reprehenderit elit tempor minim ex dolor enim veniam sit.\r\n',
    registered: '2021-10-01T11:38:07 -03:00',
    latitude: 24.165522,
    longitude: 176.212974,
    tags: ['eu', 'magna', 'deserunt', 'pariatur', 'nisi', 'cupidatat', 'eu'],
    friends: [
      {
        id: 0,
        name: 'Effie Douglas',
      },
      {
        id: 1,
        name: 'Lawanda Glenn',
      },
      {
        id: 2,
        name: 'Kaufman Holland',
      },
    ],
    greeting: 'Hello, William Lawson! You have 4 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '669b7e132779886041481df7',
    index: 1,
    guid: 'abe04b1a-ce5a-4c31-bc23-bfcc4c66633f',
    isActive: false,
    balance: '$3,396.76',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'blue',
    name: 'Richard Fuentes',
    gender: 'male',
    company: 'NITRACYR',
    email: 'richardfuentes@nitracyr.com',
    phone: '+1 (914) 572-3900',
    address: '910 Jackson Street, Osage, Hawaii, 369',
    about:
      'Dolore exercitation sit amet consequat ad incididunt minim enim veniam ullamco enim nostrud esse labore. Veniam id esse ullamco ullamco pariatur irure culpa aliqua. Eiusmod irure fugiat elit mollit voluptate ea ex labore nostrud reprehenderit. Ad proident est ex incididunt id laborum laboris qui eiusmod excepteur non.\r\n',
    registered: '2015-05-16T04:54:42 -03:00',
    latitude: 20.143927,
    longitude: 145.169622,
    tags: [
      'deserunt',
      'consectetur',
      'reprehenderit',
      'velit',
      'pariatur',
      'reprehenderit',
      'velit',
    ],
    friends: [
      {
        id: 0,
        name: 'Meyers Strickland',
      },
      {
        id: 1,
        name: 'Jenifer Boyd',
      },
      {
        id: 2,
        name: 'Deanne Colon',
      },
    ],
    greeting: 'Hello, Richard Fuentes! You have 8 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '669b7e13041e1dfc608ccbd9',
    index: 2,
    guid: '9ff594f2-98d8-4b2d-8f3b-543140acf4f1',
    isActive: true,
    balance: '$2,576.31',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'green',
    name: 'Gomez Wright',
    gender: 'male',
    company: 'NIPAZ',
    email: 'gomezwright@nipaz.com',
    phone: '+1 (852) 466-3743',
    address: '589 Everit Street, Brookfield, Louisiana, 1740',
    about:
      'Cupidatat duis ad ea voluptate velit minim. Consectetur consectetur officia nisi pariatur amet tempor adipisicing mollit excepteur exercitation Lorem sunt excepteur cupidatat. Ullamco fugiat est irure Lorem quis duis nulla laborum veniam nulla amet. Laboris laborum do deserunt mollit voluptate tempor velit occaecat duis culpa aute. Nostrud adipisicing do pariatur voluptate do esse enim cillum.\r\n',
    registered: '2018-05-14T10:28:36 -03:00',
    latitude: 68.697179,
    longitude: -151.366815,
    tags: ['aliqua', 'sit', 'consequat', 'sint', 'amet', 'aute', 'ea'],
    friends: [
      {
        id: 0,
        name: 'Arnold Mcgee',
      },
      {
        id: 1,
        name: 'Stacy Berg',
      },
      {
        id: 2,
        name: 'Goodwin Nieves',
      },
    ],
    greeting: 'Hello, Gomez Wright! You have 5 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '669b7e134b3ff966bd53f9ef',
    index: 3,
    guid: '1c5279d7-d75d-4209-ac68-c198dc5c519a',
    isActive: true,
    balance: '$1,231.02',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'brown',
    name: 'Hayden Russell',
    gender: 'male',
    company: 'PHORMULA',
    email: 'haydenrussell@phormula.com',
    phone: '+1 (882) 488-2561',
    address: '132 Java Street, Verdi, North Dakota, 5404',
    about:
      'Nostrud quis dolore incididunt laborum Lorem in laboris fugiat mollit. Sunt cupidatat irure consectetur adipisicing fugiat cillum eu Lorem duis ad sunt. Veniam pariatur dolore ea cillum aliqua sunt reprehenderit. Do magna ipsum pariatur tempor ex esse ut eiusmod commodo commodo fugiat commodo dolore. Occaecat non anim laboris aliquip magna nulla officia cupidatat tempor ea. Enim quis mollit consectetur magna.\r\n',
    registered: '2016-03-21T08:07:01 -02:00',
    latitude: -12.233664,
    longitude: -125.211848,
    tags: ['ex', 'fugiat', 'Lorem', 'occaecat', 'cillum', 'ipsum', 'tempor'],
    friends: [
      {
        id: 0,
        name: 'Banks Sargent',
      },
      {
        id: 1,
        name: 'Brandi English',
      },
      {
        id: 2,
        name: 'Priscilla Parker',
      },
    ],
    greeting: 'Hello, Hayden Russell! You have 2 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '669b7e139169dd6c59d7f921',
    index: 4,
    guid: 'dae566bb-c428-4799-aa1e-cb47cf7a729f',
    isActive: true,
    balance: '$3,736.38',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'brown',
    name: 'Callie Kramer',
    gender: 'female',
    company: 'EXERTA',
    email: 'calliekramer@exerta.com',
    phone: '+1 (867) 537-2242',
    address: '776 Bergen Avenue, Bannock, Florida, 2128',
    about:
      'Eu est sint sit enim ullamco consequat anim excepteur cupidatat proident nostrud amet qui cillum. Ad qui ullamco nisi minim consequat magna commodo fugiat fugiat. Mollit in eiusmod dolor eu pariatur non do anim nulla cupidatat excepteur dolor est.\r\n',
    registered: '2019-07-20T07:07:58 -03:00',
    latitude: 74.170763,
    longitude: -140.919724,
    tags: [
      'Lorem',
      'incididunt',
      'voluptate',
      'cillum',
      'qui',
      'tempor',
      'consequat',
    ],
    friends: [
      {
        id: 0,
        name: 'Kimberley Pennington',
      },
      {
        id: 1,
        name: 'Nona Huff',
      },
      {
        id: 2,
        name: 'Whitehead Huffman',
      },
    ],
    greeting: 'Hello, Callie Kramer! You have 3 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '669b7e13d3e924c5e2f80abb',
    index: 5,
    guid: '3be1a7df-f439-4799-9c7b-07b90472e484',
    isActive: true,
    balance: '$2,163.38',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'blue',
    name: 'Cecelia Lawrence',
    gender: 'female',
    company: 'GEEKOLOGY',
    email: 'cecelialawrence@geekology.com',
    phone: '+1 (842) 563-2785',
    address: '804 Ridgecrest Terrace, Crayne, New Hampshire, 6229',
    about:
      'Et sunt fugiat culpa Lorem anim duis ut. Incididunt elit occaecat aliqua voluptate et aliquip ea et. Laborum et ad ad culpa magna magna ad commodo magna Lorem proident.\r\n',
    registered: '2019-07-20T10:43:04 -03:00',
    latitude: -29.233781,
    longitude: 166.580636,
    tags: [
      'consectetur',
      'ut',
      'proident',
      'voluptate',
      'anim',
      'et',
      'voluptate',
    ],
    friends: [
      {
        id: 0,
        name: 'Dotson Bradshaw',
      },
      {
        id: 1,
        name: 'Leslie Gillespie',
      },
      {
        id: 2,
        name: 'Griffith Coffey',
      },
    ],
    greeting: 'Hello, Cecelia Lawrence! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
];
